# Change these first
owner: BLANC-Fashion # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: BLANC Showroom
    url: https://blancfashion.com/
  - name: Platform API v1
    url: https://api.blancfashion.com/
  - name: Platform API v2
    url: https://new.api.blancfashion.com/
  - name: Automation Service
    url: $N8N_SERVICES

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://d1zcksbvpzkc0o.cloudfront.net/account/logo/4a7a6b9e4c9b11ed86240eca71e26a7a.png
  name: BLANC Status Page
  introTitle: "Follow the status of our main services"
  introMessage: This is a sample status page for [BLANC](https://blancfashion.com)
  navbar:
    - title: Status
      href: /
    - title: Go to BLANC
      href: https://blancfashion.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
